# Generated by Django 6.0.3 on 2026-03-30 10:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name="Type d'absence")),
                ('impacts_quota', models.BooleanField(default=True, verbose_name='Impacte le quota de congés')),
            ],
            options={
                'verbose_name': "Type d'absence",
                'verbose_name_plural': "Types d'absence",
                'db_table': 'absence_type',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom de la certification')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'db_table': 'certification',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type de contrat')),
                ('max_hours_per_week', models.IntegerField(blank=True, null=True, verbose_name='Heures max/semaine')),
                ('leave_days_per_year', models.IntegerField(blank=True, null=True, verbose_name='Jours de congés/an')),
                ('night_shift_allowed', models.BooleanField(default=True, verbose_name='Garde de nuit autorisée')),
            ],
            options={
                'verbose_name': 'Type de contrat',
                'verbose_name_plural': 'Types de contrat',
                'db_table': 'contract_type',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du rôle')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la règle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('rule_type', models.CharField(choices=[('max_hours', 'Heures maximum'), ('rest_time', 'Temps de repos'), ('min_staff', 'Effectif minimum'), ('max_consecutive_days', 'Jours consécutifs max')], max_length=50, verbose_name='Type de règle')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur')),
                ('unit', models.CharField(max_length=20, verbose_name='Unité')),
                ('valid_from', models.DateField(verbose_name='Valide depuis')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'à")),
            ],
            options={
                'verbose_name': 'Règle',
                'verbose_name_plural': 'Règles',
                'db_table': 'rule',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du service')),
                ('bed_capacity', models.IntegerField(verbose_name='Capacité en lits')),
                ('criticality_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Niveau de criticité (1-5)')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Type de garde')),
                ('duration_hours', models.IntegerField(verbose_name='Durée (heures)')),
                ('requires_rest_after', models.BooleanField(default=True, verbose_name='Repos obligatoire après')),
            ],
            options={
                'verbose_name': 'Type de garde',
                'verbose_name_plural': 'Types de garde',
                'db_table': 'shift_type',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Soignant',
                'verbose_name_plural': 'Soignants',
                'db_table': 'staff',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CareUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'unité")),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_units', to='planning.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Unité de soins',
                'verbose_name_plural': 'Unités de soins',
                'db_table': 'care_unit',
                'unique_together': {('service', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé'), ('sous_effectif', 'Sous-effectif')], max_length=50, verbose_name='Statut')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='planning.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Statut de service',
                'verbose_name_plural': 'Statuts de service',
                'db_table': 'service_status',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Début')),
                ('end_datetime', models.DateTimeField(verbose_name='Fin')),
                ('min_staff', models.IntegerField(default=1, verbose_name='Effectif minimum')),
                ('max_staff', models.IntegerField(blank=True, null=True, verbose_name='Effectif maximum')),
                ('care_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='planning.careunit', verbose_name='Unité de soins')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shifts', to='planning.shifttype', verbose_name='Type de garde')),
            ],
            options={
                'verbose_name': 'Poste de garde',
                'verbose_name_plural': 'Postes de garde',
                'db_table': 'shift',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la spécialité')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='planning.specialty', verbose_name='Spécialité parente')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'db_table': 'specialty',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_services', to='planning.staff', verbose_name='Responsable'),
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('preference', 'Préférence'), ('constraint', 'Contrainte')], max_length=50, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_hard_constraint', models.BooleanField(default=False, verbose_name='Contrainte impérative')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='planning.staff', verbose_name='Soignant')),
            ],
            options={
                'verbose_name': 'Préférence',
                'verbose_name_plural': 'Préférences',
                'db_table': 'preference',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('workload_percent', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Temps de travail (%)')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contracts', to='planning.contracttype', verbose_name='Type de contrat')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='planning.staff', verbose_name='Soignant')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'db_table': 'contract',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('expected_end_date', models.DateField(verbose_name='Date de fin prévue')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('is_planned', models.BooleanField(default=True, verbose_name='Planifiée')),
                ('absence_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='absences', to='planning.absencetype', verbose_name="Type d'absence")),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='planning.staff', verbose_name='Soignant')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'db_table': 'absence',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('from_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_loaned_out', to='planning.service', verbose_name="Service d'origine")),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='planning.staff', verbose_name='Soignant')),
                ('to_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_loaned_in', to='planning.service', verbose_name="Service d'accueil")),
            ],
            options={
                'verbose_name': 'Prêt de personnel',
                'verbose_name_plural': 'Prêts de personnel',
                'db_table': 'staff_loan',
            },
        ),
        migrations.CreateModel(
            name='StaffServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='planning.service', verbose_name='Service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='planning.staff', verbose_name='Soignant')),
            ],
            options={
                'verbose_name': 'Affectation au service',
                'verbose_name_plural': 'Affectations aux services',
                'db_table': 'staff_service_assignment',
            },
        ),
        migrations.CreateModel(
            name='CertificationDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='planning.certification', verbose_name='Certification')),
                ('required_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='planning.certification', verbose_name='Certification requise')),
            ],
            options={
                'verbose_name': 'Dépendance de certification',
                'verbose_name_plural': 'Dépendances de certification',
                'db_table': 'certification_dependency',
                'unique_together': {('parent_cert', 'required_cert')},
            },
        ),
        migrations.CreateModel(
            name='PatientLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('patient_count', models.IntegerField(verbose_name='Nombre de patients')),
                ('occupancy_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Taux d'occupation (%)")),
                ('care_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_loads', to='planning.careunit', verbose_name='Unité de soins')),
            ],
            options={
                'verbose_name': 'Charge patient',
                'verbose_name_plural': 'Charges patient',
                'db_table': 'patient_load',
                'unique_together': {('care_unit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ShiftRequiredCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_shifts', to='planning.certification', verbose_name='Certification requise')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_certifications', to='planning.shift', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Certification requise pour le poste',
                'verbose_name_plural': 'Certifications requises pour les postes',
                'db_table': 'shift_required_certification',
                'unique_together': {('shift', 'certification')},
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Affecté le')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='planning.shift', verbose_name='Poste')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='planning.staff', verbose_name='Soignant')),
            ],
            options={
                'verbose_name': 'Affectation au poste',
                'verbose_name_plural': 'Affectations aux postes',
                'db_table': 'shift_assignment',
                'unique_together': {('shift', 'staff')},
            },
        ),
        migrations.CreateModel(
            name='StaffCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_date', models.DateField(verbose_name="Date d'obtention")),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_certifications', to='planning.certification', verbose_name='Certification')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='planning.staff', verbose_name='Soignant')),
            ],
            options={
                'verbose_name': 'Certification du soignant',
                'verbose_name_plural': 'Certifications des soignants',
                'db_table': 'staff_certification',
                'unique_together': {('staff', 'certification')},
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='planning.role', verbose_name='Rôle')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='planning.staff', verbose_name='Soignant')),
            ],
            options={
                'verbose_name': 'Rôle du soignant',
                'verbose_name_plural': 'Rôles des soignants',
                'db_table': 'staff_role',
                'unique_together': {('staff', 'role')},
            },
        ),
        migrations.CreateModel(
            name='StaffSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_specialties', to='planning.specialty', verbose_name='Spécialité')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_specialties', to='planning.staff', verbose_name='Soignant')),
            ],
            options={
                'verbose_name': 'Spécialité du soignant',
                'verbose_name_plural': 'Spécialités des soignants',
                'db_table': 'staff_specialty',
                'unique_together': {('staff', 'specialty')},
            },
        ),
    ]
